image: "rust:latest"

stages:
  - build
  - test

build:
  stage: build
  script:
    - rustc --version && cargo --version
    - cargo build
  artifacts:
    paths:
        - target/

cargo-unit-tests:
  stage: test
  script:
    - cargo test --all --verbose

end-to-end-tests:
  stage: test
  script:
    - apt-get update
    - apt-get install -y netcat
    - ./test_server.sh
