language: rust

rust:
  - stable

os:
  - linux

dist:
  - bionic

addons:
  apt:
    update: true
    packages:
      - netcat-openbsd

script:
  - cargo build --verbose
  - cargo test --verbose
  - ./test_server.sh
